CREATE TABLE IF NOT EXISTS creator_channels(id TEXT PRIMARY KEY,youtube_id TEXT UNIQUE NOT NULL,title TEXT NOT NULL,subscribers INTEGER,observed_at TEXT);
CREATE TABLE IF NOT EXISTS videos(id TEXT PRIMARY KEY,youtube_id TEXT UNIQUE NOT NULL,creator_channel_id TEXT NOT NULL REFERENCES creator_channels(id),title TEXT NOT NULL,published_at TEXT NOT NULL,duration_s INTEGER,kind TEXT NOT NULL,thumbnail_url TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS ix_videos_published ON videos(published_at);
CREATE TABLE IF NOT EXISTS source_runs(id TEXT PRIMARY KEY,keyword TEXT NOT NULL,region TEXT NOT NULL,window_days INTEGER NOT NULL,requested_at TEXT NOT NULL,completed_at TEXT,status TEXT NOT NULL,result_count INTEGER NOT NULL DEFAULT 0,error_code TEXT,coverage_note TEXT);
CREATE TABLE IF NOT EXISTS source_records(run_id TEXT NOT NULL REFERENCES source_runs(id),video_id TEXT NOT NULL REFERENCES videos(id),rank INTEGER NOT NULL,PRIMARY KEY(run_id,video_id));
CREATE TABLE IF NOT EXISTS video_snapshots(id TEXT PRIMARY KEY,video_id TEXT NOT NULL REFERENCES videos(id),views INTEGER,likes INTEGER,comments INTEGER,captured_at TEXT NOT NULL,source_run_id TEXT REFERENCES source_runs(id),source TEXT NOT NULL,UNIQUE(video_id,captured_at));
CREATE INDEX IF NOT EXISTS ix_snapshots_video ON video_snapshots(video_id,captured_at);
CREATE TABLE IF NOT EXISTS research_analyses(id TEXT PRIMARY KEY,video_id TEXT NOT NULL REFERENCES videos(id),title_rubric TEXT NOT NULL,thumbnail_rubric TEXT NOT NULL,visual_evidence TEXT NOT NULL,review_note TEXT NOT NULL,click_appeal REAL NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS research_opportunities(id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES source_runs(id),target_channel_id TEXT NOT NULL REFERENCES channels(id),topic TEXT NOT NULL,difficulty INTEGER,trend_score REAL,outlier_evidence REAL,click_appeal REAL,score REAL,missing_json TEXT NOT NULL,components_json TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(run_id,target_channel_id));
